# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jelle/src/VoyeSeqProject

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jelle/src/VoyeSeqProject/src

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jelle/src/VoyeSeqProject/src/CMakeFiles /home/jelle/src/VoyeSeqProject/src//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jelle/src/VoyeSeqProject/src/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named dgl-opengl

# Build rule for target.
dgl-opengl: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 dgl-opengl
.PHONY : dgl-opengl

# fast build rule for target.
dgl-opengl/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dgl-opengl.dir/build.make CMakeFiles/dgl-opengl.dir/build
.PHONY : dgl-opengl/fast

#=============================================================================
# Target rules for targets named VoyeSeq

# Build rule for target.
VoyeSeq: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 VoyeSeq
.PHONY : VoyeSeq

# fast build rule for target.
VoyeSeq/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VoyeSeq.dir/build.make CMakeFiles/VoyeSeq.dir/build
.PHONY : VoyeSeq/fast

#=============================================================================
# Target rules for targets named VoyeSeq-dsp

# Build rule for target.
VoyeSeq-dsp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 VoyeSeq-dsp
.PHONY : VoyeSeq-dsp

# fast build rule for target.
VoyeSeq-dsp/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VoyeSeq-dsp.dir/build.make CMakeFiles/VoyeSeq-dsp.dir/build
.PHONY : VoyeSeq-dsp/fast

#=============================================================================
# Target rules for targets named VoyeSeq-ui

# Build rule for target.
VoyeSeq-ui: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 VoyeSeq-ui
.PHONY : VoyeSeq-ui

# fast build rule for target.
VoyeSeq-ui/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VoyeSeq-ui.dir/build.make CMakeFiles/VoyeSeq-ui.dir/build
.PHONY : VoyeSeq-ui/fast

#=============================================================================
# Target rules for targets named VoyeSeq-jack

# Build rule for target.
VoyeSeq-jack: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 VoyeSeq-jack
.PHONY : VoyeSeq-jack

# fast build rule for target.
VoyeSeq-jack/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VoyeSeq-jack.dir/build.make CMakeFiles/VoyeSeq-jack.dir/build
.PHONY : VoyeSeq-jack/fast

#=============================================================================
# Target rules for targets named VoyeSeq-lv2

# Build rule for target.
VoyeSeq-lv2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 VoyeSeq-lv2
.PHONY : VoyeSeq-lv2

# fast build rule for target.
VoyeSeq-lv2/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VoyeSeq-lv2.dir/build.make CMakeFiles/VoyeSeq-lv2.dir/build
.PHONY : VoyeSeq-lv2/fast

#=============================================================================
# Target rules for targets named VoyeSeq-lv2-ui

# Build rule for target.
VoyeSeq-lv2-ui: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 VoyeSeq-lv2-ui
.PHONY : VoyeSeq-lv2-ui

# fast build rule for target.
VoyeSeq-lv2-ui/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VoyeSeq-lv2-ui.dir/build.make CMakeFiles/VoyeSeq-lv2-ui.dir/build
.PHONY : VoyeSeq-lv2-ui/fast

#=============================================================================
# Target rules for targets named lv2_ttl_generator

# Build rule for target.
lv2_ttl_generator: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lv2_ttl_generator
.PHONY : lv2_ttl_generator

# fast build rule for target.
lv2_ttl_generator/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lv2_ttl_generator.dir/build.make CMakeFiles/lv2_ttl_generator.dir/build
.PHONY : lv2_ttl_generator/fast

VoyeRenderer.o: VoyeRenderer.cpp.o
.PHONY : VoyeRenderer.o

# target to build an object file
VoyeRenderer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VoyeSeq-ui.dir/build.make CMakeFiles/VoyeSeq-ui.dir/VoyeRenderer.cpp.o
.PHONY : VoyeRenderer.cpp.o

VoyeRenderer.i: VoyeRenderer.cpp.i
.PHONY : VoyeRenderer.i

# target to preprocess a source file
VoyeRenderer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VoyeSeq-ui.dir/build.make CMakeFiles/VoyeSeq-ui.dir/VoyeRenderer.cpp.i
.PHONY : VoyeRenderer.cpp.i

VoyeRenderer.s: VoyeRenderer.cpp.s
.PHONY : VoyeRenderer.s

# target to generate assembly for a file
VoyeRenderer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VoyeSeq-ui.dir/build.make CMakeFiles/VoyeSeq-ui.dir/VoyeRenderer.cpp.s
.PHONY : VoyeRenderer.cpp.s

VoyeSeqPlugin.o: VoyeSeqPlugin.cpp.o
.PHONY : VoyeSeqPlugin.o

# target to build an object file
VoyeSeqPlugin.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VoyeSeq-dsp.dir/build.make CMakeFiles/VoyeSeq-dsp.dir/VoyeSeqPlugin.cpp.o
.PHONY : VoyeSeqPlugin.cpp.o

VoyeSeqPlugin.i: VoyeSeqPlugin.cpp.i
.PHONY : VoyeSeqPlugin.i

# target to preprocess a source file
VoyeSeqPlugin.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VoyeSeq-dsp.dir/build.make CMakeFiles/VoyeSeq-dsp.dir/VoyeSeqPlugin.cpp.i
.PHONY : VoyeSeqPlugin.cpp.i

VoyeSeqPlugin.s: VoyeSeqPlugin.cpp.s
.PHONY : VoyeSeqPlugin.s

# target to generate assembly for a file
VoyeSeqPlugin.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VoyeSeq-dsp.dir/build.make CMakeFiles/VoyeSeq-dsp.dir/VoyeSeqPlugin.cpp.s
.PHONY : VoyeSeqPlugin.cpp.s

VoyeSeqUI.o: VoyeSeqUI.cpp.o
.PHONY : VoyeSeqUI.o

# target to build an object file
VoyeSeqUI.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VoyeSeq-ui.dir/build.make CMakeFiles/VoyeSeq-ui.dir/VoyeSeqUI.cpp.o
.PHONY : VoyeSeqUI.cpp.o

VoyeSeqUI.i: VoyeSeqUI.cpp.i
.PHONY : VoyeSeqUI.i

# target to preprocess a source file
VoyeSeqUI.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VoyeSeq-ui.dir/build.make CMakeFiles/VoyeSeq-ui.dir/VoyeSeqUI.cpp.i
.PHONY : VoyeSeqUI.cpp.i

VoyeSeqUI.s: VoyeSeqUI.cpp.s
.PHONY : VoyeSeqUI.s

# target to generate assembly for a file
VoyeSeqUI.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VoyeSeq-ui.dir/build.make CMakeFiles/VoyeSeq-ui.dir/VoyeSeqUI.cpp.s
.PHONY : VoyeSeqUI.cpp.s

_dpf_empty.o: _dpf_empty.c.o
.PHONY : _dpf_empty.o

# target to build an object file
_dpf_empty.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VoyeSeq.dir/build.make CMakeFiles/VoyeSeq.dir/_dpf_empty.c.o
.PHONY : _dpf_empty.c.o

_dpf_empty.i: _dpf_empty.c.i
.PHONY : _dpf_empty.i

# target to preprocess a source file
_dpf_empty.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VoyeSeq.dir/build.make CMakeFiles/VoyeSeq.dir/_dpf_empty.c.i
.PHONY : _dpf_empty.c.i

_dpf_empty.s: _dpf_empty.c.s
.PHONY : _dpf_empty.s

# target to generate assembly for a file
_dpf_empty.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VoyeSeq.dir/build.make CMakeFiles/VoyeSeq.dir/_dpf_empty.c.s
.PHONY : _dpf_empty.c.s

dpf/dgl/src/Application.o: dpf/dgl/src/Application.cpp.o
.PHONY : dpf/dgl/src/Application.o

# target to build an object file
dpf/dgl/src/Application.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dgl-opengl.dir/build.make CMakeFiles/dgl-opengl.dir/dpf/dgl/src/Application.cpp.o
.PHONY : dpf/dgl/src/Application.cpp.o

dpf/dgl/src/Application.i: dpf/dgl/src/Application.cpp.i
.PHONY : dpf/dgl/src/Application.i

# target to preprocess a source file
dpf/dgl/src/Application.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dgl-opengl.dir/build.make CMakeFiles/dgl-opengl.dir/dpf/dgl/src/Application.cpp.i
.PHONY : dpf/dgl/src/Application.cpp.i

dpf/dgl/src/Application.s: dpf/dgl/src/Application.cpp.s
.PHONY : dpf/dgl/src/Application.s

# target to generate assembly for a file
dpf/dgl/src/Application.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dgl-opengl.dir/build.make CMakeFiles/dgl-opengl.dir/dpf/dgl/src/Application.cpp.s
.PHONY : dpf/dgl/src/Application.cpp.s

dpf/dgl/src/ApplicationPrivateData.o: dpf/dgl/src/ApplicationPrivateData.cpp.o
.PHONY : dpf/dgl/src/ApplicationPrivateData.o

# target to build an object file
dpf/dgl/src/ApplicationPrivateData.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dgl-opengl.dir/build.make CMakeFiles/dgl-opengl.dir/dpf/dgl/src/ApplicationPrivateData.cpp.o
.PHONY : dpf/dgl/src/ApplicationPrivateData.cpp.o

dpf/dgl/src/ApplicationPrivateData.i: dpf/dgl/src/ApplicationPrivateData.cpp.i
.PHONY : dpf/dgl/src/ApplicationPrivateData.i

# target to preprocess a source file
dpf/dgl/src/ApplicationPrivateData.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dgl-opengl.dir/build.make CMakeFiles/dgl-opengl.dir/dpf/dgl/src/ApplicationPrivateData.cpp.i
.PHONY : dpf/dgl/src/ApplicationPrivateData.cpp.i

dpf/dgl/src/ApplicationPrivateData.s: dpf/dgl/src/ApplicationPrivateData.cpp.s
.PHONY : dpf/dgl/src/ApplicationPrivateData.s

# target to generate assembly for a file
dpf/dgl/src/ApplicationPrivateData.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dgl-opengl.dir/build.make CMakeFiles/dgl-opengl.dir/dpf/dgl/src/ApplicationPrivateData.cpp.s
.PHONY : dpf/dgl/src/ApplicationPrivateData.cpp.s

dpf/dgl/src/Color.o: dpf/dgl/src/Color.cpp.o
.PHONY : dpf/dgl/src/Color.o

# target to build an object file
dpf/dgl/src/Color.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dgl-opengl.dir/build.make CMakeFiles/dgl-opengl.dir/dpf/dgl/src/Color.cpp.o
.PHONY : dpf/dgl/src/Color.cpp.o

dpf/dgl/src/Color.i: dpf/dgl/src/Color.cpp.i
.PHONY : dpf/dgl/src/Color.i

# target to preprocess a source file
dpf/dgl/src/Color.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dgl-opengl.dir/build.make CMakeFiles/dgl-opengl.dir/dpf/dgl/src/Color.cpp.i
.PHONY : dpf/dgl/src/Color.cpp.i

dpf/dgl/src/Color.s: dpf/dgl/src/Color.cpp.s
.PHONY : dpf/dgl/src/Color.s

# target to generate assembly for a file
dpf/dgl/src/Color.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dgl-opengl.dir/build.make CMakeFiles/dgl-opengl.dir/dpf/dgl/src/Color.cpp.s
.PHONY : dpf/dgl/src/Color.cpp.s

dpf/dgl/src/EventHandlers.o: dpf/dgl/src/EventHandlers.cpp.o
.PHONY : dpf/dgl/src/EventHandlers.o

# target to build an object file
dpf/dgl/src/EventHandlers.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dgl-opengl.dir/build.make CMakeFiles/dgl-opengl.dir/dpf/dgl/src/EventHandlers.cpp.o
.PHONY : dpf/dgl/src/EventHandlers.cpp.o

dpf/dgl/src/EventHandlers.i: dpf/dgl/src/EventHandlers.cpp.i
.PHONY : dpf/dgl/src/EventHandlers.i

# target to preprocess a source file
dpf/dgl/src/EventHandlers.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dgl-opengl.dir/build.make CMakeFiles/dgl-opengl.dir/dpf/dgl/src/EventHandlers.cpp.i
.PHONY : dpf/dgl/src/EventHandlers.cpp.i

dpf/dgl/src/EventHandlers.s: dpf/dgl/src/EventHandlers.cpp.s
.PHONY : dpf/dgl/src/EventHandlers.s

# target to generate assembly for a file
dpf/dgl/src/EventHandlers.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dgl-opengl.dir/build.make CMakeFiles/dgl-opengl.dir/dpf/dgl/src/EventHandlers.cpp.s
.PHONY : dpf/dgl/src/EventHandlers.cpp.s

dpf/dgl/src/Geometry.o: dpf/dgl/src/Geometry.cpp.o
.PHONY : dpf/dgl/src/Geometry.o

# target to build an object file
dpf/dgl/src/Geometry.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dgl-opengl.dir/build.make CMakeFiles/dgl-opengl.dir/dpf/dgl/src/Geometry.cpp.o
.PHONY : dpf/dgl/src/Geometry.cpp.o

dpf/dgl/src/Geometry.i: dpf/dgl/src/Geometry.cpp.i
.PHONY : dpf/dgl/src/Geometry.i

# target to preprocess a source file
dpf/dgl/src/Geometry.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dgl-opengl.dir/build.make CMakeFiles/dgl-opengl.dir/dpf/dgl/src/Geometry.cpp.i
.PHONY : dpf/dgl/src/Geometry.cpp.i

dpf/dgl/src/Geometry.s: dpf/dgl/src/Geometry.cpp.s
.PHONY : dpf/dgl/src/Geometry.s

# target to generate assembly for a file
dpf/dgl/src/Geometry.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dgl-opengl.dir/build.make CMakeFiles/dgl-opengl.dir/dpf/dgl/src/Geometry.cpp.s
.PHONY : dpf/dgl/src/Geometry.cpp.s

dpf/dgl/src/ImageBase.o: dpf/dgl/src/ImageBase.cpp.o
.PHONY : dpf/dgl/src/ImageBase.o

# target to build an object file
dpf/dgl/src/ImageBase.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dgl-opengl.dir/build.make CMakeFiles/dgl-opengl.dir/dpf/dgl/src/ImageBase.cpp.o
.PHONY : dpf/dgl/src/ImageBase.cpp.o

dpf/dgl/src/ImageBase.i: dpf/dgl/src/ImageBase.cpp.i
.PHONY : dpf/dgl/src/ImageBase.i

# target to preprocess a source file
dpf/dgl/src/ImageBase.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dgl-opengl.dir/build.make CMakeFiles/dgl-opengl.dir/dpf/dgl/src/ImageBase.cpp.i
.PHONY : dpf/dgl/src/ImageBase.cpp.i

dpf/dgl/src/ImageBase.s: dpf/dgl/src/ImageBase.cpp.s
.PHONY : dpf/dgl/src/ImageBase.s

# target to generate assembly for a file
dpf/dgl/src/ImageBase.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dgl-opengl.dir/build.make CMakeFiles/dgl-opengl.dir/dpf/dgl/src/ImageBase.cpp.s
.PHONY : dpf/dgl/src/ImageBase.cpp.s

dpf/dgl/src/ImageBaseWidgets.o: dpf/dgl/src/ImageBaseWidgets.cpp.o
.PHONY : dpf/dgl/src/ImageBaseWidgets.o

# target to build an object file
dpf/dgl/src/ImageBaseWidgets.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dgl-opengl.dir/build.make CMakeFiles/dgl-opengl.dir/dpf/dgl/src/ImageBaseWidgets.cpp.o
.PHONY : dpf/dgl/src/ImageBaseWidgets.cpp.o

dpf/dgl/src/ImageBaseWidgets.i: dpf/dgl/src/ImageBaseWidgets.cpp.i
.PHONY : dpf/dgl/src/ImageBaseWidgets.i

# target to preprocess a source file
dpf/dgl/src/ImageBaseWidgets.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dgl-opengl.dir/build.make CMakeFiles/dgl-opengl.dir/dpf/dgl/src/ImageBaseWidgets.cpp.i
.PHONY : dpf/dgl/src/ImageBaseWidgets.cpp.i

dpf/dgl/src/ImageBaseWidgets.s: dpf/dgl/src/ImageBaseWidgets.cpp.s
.PHONY : dpf/dgl/src/ImageBaseWidgets.s

# target to generate assembly for a file
dpf/dgl/src/ImageBaseWidgets.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dgl-opengl.dir/build.make CMakeFiles/dgl-opengl.dir/dpf/dgl/src/ImageBaseWidgets.cpp.s
.PHONY : dpf/dgl/src/ImageBaseWidgets.cpp.s

dpf/dgl/src/Layout.o: dpf/dgl/src/Layout.cpp.o
.PHONY : dpf/dgl/src/Layout.o

# target to build an object file
dpf/dgl/src/Layout.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dgl-opengl.dir/build.make CMakeFiles/dgl-opengl.dir/dpf/dgl/src/Layout.cpp.o
.PHONY : dpf/dgl/src/Layout.cpp.o

dpf/dgl/src/Layout.i: dpf/dgl/src/Layout.cpp.i
.PHONY : dpf/dgl/src/Layout.i

# target to preprocess a source file
dpf/dgl/src/Layout.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dgl-opengl.dir/build.make CMakeFiles/dgl-opengl.dir/dpf/dgl/src/Layout.cpp.i
.PHONY : dpf/dgl/src/Layout.cpp.i

dpf/dgl/src/Layout.s: dpf/dgl/src/Layout.cpp.s
.PHONY : dpf/dgl/src/Layout.s

# target to generate assembly for a file
dpf/dgl/src/Layout.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dgl-opengl.dir/build.make CMakeFiles/dgl-opengl.dir/dpf/dgl/src/Layout.cpp.s
.PHONY : dpf/dgl/src/Layout.cpp.s

dpf/dgl/src/NanoVG.o: dpf/dgl/src/NanoVG.cpp.o
.PHONY : dpf/dgl/src/NanoVG.o

# target to build an object file
dpf/dgl/src/NanoVG.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dgl-opengl.dir/build.make CMakeFiles/dgl-opengl.dir/dpf/dgl/src/NanoVG.cpp.o
.PHONY : dpf/dgl/src/NanoVG.cpp.o

dpf/dgl/src/NanoVG.i: dpf/dgl/src/NanoVG.cpp.i
.PHONY : dpf/dgl/src/NanoVG.i

# target to preprocess a source file
dpf/dgl/src/NanoVG.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dgl-opengl.dir/build.make CMakeFiles/dgl-opengl.dir/dpf/dgl/src/NanoVG.cpp.i
.PHONY : dpf/dgl/src/NanoVG.cpp.i

dpf/dgl/src/NanoVG.s: dpf/dgl/src/NanoVG.cpp.s
.PHONY : dpf/dgl/src/NanoVG.s

# target to generate assembly for a file
dpf/dgl/src/NanoVG.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dgl-opengl.dir/build.make CMakeFiles/dgl-opengl.dir/dpf/dgl/src/NanoVG.cpp.s
.PHONY : dpf/dgl/src/NanoVG.cpp.s

dpf/dgl/src/OpenGL.o: dpf/dgl/src/OpenGL.cpp.o
.PHONY : dpf/dgl/src/OpenGL.o

# target to build an object file
dpf/dgl/src/OpenGL.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dgl-opengl.dir/build.make CMakeFiles/dgl-opengl.dir/dpf/dgl/src/OpenGL.cpp.o
.PHONY : dpf/dgl/src/OpenGL.cpp.o

dpf/dgl/src/OpenGL.i: dpf/dgl/src/OpenGL.cpp.i
.PHONY : dpf/dgl/src/OpenGL.i

# target to preprocess a source file
dpf/dgl/src/OpenGL.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dgl-opengl.dir/build.make CMakeFiles/dgl-opengl.dir/dpf/dgl/src/OpenGL.cpp.i
.PHONY : dpf/dgl/src/OpenGL.cpp.i

dpf/dgl/src/OpenGL.s: dpf/dgl/src/OpenGL.cpp.s
.PHONY : dpf/dgl/src/OpenGL.s

# target to generate assembly for a file
dpf/dgl/src/OpenGL.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dgl-opengl.dir/build.make CMakeFiles/dgl-opengl.dir/dpf/dgl/src/OpenGL.cpp.s
.PHONY : dpf/dgl/src/OpenGL.cpp.s

dpf/dgl/src/OpenGL2.o: dpf/dgl/src/OpenGL2.cpp.o
.PHONY : dpf/dgl/src/OpenGL2.o

# target to build an object file
dpf/dgl/src/OpenGL2.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dgl-opengl.dir/build.make CMakeFiles/dgl-opengl.dir/dpf/dgl/src/OpenGL2.cpp.o
.PHONY : dpf/dgl/src/OpenGL2.cpp.o

dpf/dgl/src/OpenGL2.i: dpf/dgl/src/OpenGL2.cpp.i
.PHONY : dpf/dgl/src/OpenGL2.i

# target to preprocess a source file
dpf/dgl/src/OpenGL2.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dgl-opengl.dir/build.make CMakeFiles/dgl-opengl.dir/dpf/dgl/src/OpenGL2.cpp.i
.PHONY : dpf/dgl/src/OpenGL2.cpp.i

dpf/dgl/src/OpenGL2.s: dpf/dgl/src/OpenGL2.cpp.s
.PHONY : dpf/dgl/src/OpenGL2.s

# target to generate assembly for a file
dpf/dgl/src/OpenGL2.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dgl-opengl.dir/build.make CMakeFiles/dgl-opengl.dir/dpf/dgl/src/OpenGL2.cpp.s
.PHONY : dpf/dgl/src/OpenGL2.cpp.s

dpf/dgl/src/Resources.o: dpf/dgl/src/Resources.cpp.o
.PHONY : dpf/dgl/src/Resources.o

# target to build an object file
dpf/dgl/src/Resources.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dgl-opengl.dir/build.make CMakeFiles/dgl-opengl.dir/dpf/dgl/src/Resources.cpp.o
.PHONY : dpf/dgl/src/Resources.cpp.o

dpf/dgl/src/Resources.i: dpf/dgl/src/Resources.cpp.i
.PHONY : dpf/dgl/src/Resources.i

# target to preprocess a source file
dpf/dgl/src/Resources.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dgl-opengl.dir/build.make CMakeFiles/dgl-opengl.dir/dpf/dgl/src/Resources.cpp.i
.PHONY : dpf/dgl/src/Resources.cpp.i

dpf/dgl/src/Resources.s: dpf/dgl/src/Resources.cpp.s
.PHONY : dpf/dgl/src/Resources.s

# target to generate assembly for a file
dpf/dgl/src/Resources.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dgl-opengl.dir/build.make CMakeFiles/dgl-opengl.dir/dpf/dgl/src/Resources.cpp.s
.PHONY : dpf/dgl/src/Resources.cpp.s

dpf/dgl/src/SubWidget.o: dpf/dgl/src/SubWidget.cpp.o
.PHONY : dpf/dgl/src/SubWidget.o

# target to build an object file
dpf/dgl/src/SubWidget.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dgl-opengl.dir/build.make CMakeFiles/dgl-opengl.dir/dpf/dgl/src/SubWidget.cpp.o
.PHONY : dpf/dgl/src/SubWidget.cpp.o

dpf/dgl/src/SubWidget.i: dpf/dgl/src/SubWidget.cpp.i
.PHONY : dpf/dgl/src/SubWidget.i

# target to preprocess a source file
dpf/dgl/src/SubWidget.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dgl-opengl.dir/build.make CMakeFiles/dgl-opengl.dir/dpf/dgl/src/SubWidget.cpp.i
.PHONY : dpf/dgl/src/SubWidget.cpp.i

dpf/dgl/src/SubWidget.s: dpf/dgl/src/SubWidget.cpp.s
.PHONY : dpf/dgl/src/SubWidget.s

# target to generate assembly for a file
dpf/dgl/src/SubWidget.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dgl-opengl.dir/build.make CMakeFiles/dgl-opengl.dir/dpf/dgl/src/SubWidget.cpp.s
.PHONY : dpf/dgl/src/SubWidget.cpp.s

dpf/dgl/src/SubWidgetPrivateData.o: dpf/dgl/src/SubWidgetPrivateData.cpp.o
.PHONY : dpf/dgl/src/SubWidgetPrivateData.o

# target to build an object file
dpf/dgl/src/SubWidgetPrivateData.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dgl-opengl.dir/build.make CMakeFiles/dgl-opengl.dir/dpf/dgl/src/SubWidgetPrivateData.cpp.o
.PHONY : dpf/dgl/src/SubWidgetPrivateData.cpp.o

dpf/dgl/src/SubWidgetPrivateData.i: dpf/dgl/src/SubWidgetPrivateData.cpp.i
.PHONY : dpf/dgl/src/SubWidgetPrivateData.i

# target to preprocess a source file
dpf/dgl/src/SubWidgetPrivateData.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dgl-opengl.dir/build.make CMakeFiles/dgl-opengl.dir/dpf/dgl/src/SubWidgetPrivateData.cpp.i
.PHONY : dpf/dgl/src/SubWidgetPrivateData.cpp.i

dpf/dgl/src/SubWidgetPrivateData.s: dpf/dgl/src/SubWidgetPrivateData.cpp.s
.PHONY : dpf/dgl/src/SubWidgetPrivateData.s

# target to generate assembly for a file
dpf/dgl/src/SubWidgetPrivateData.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dgl-opengl.dir/build.make CMakeFiles/dgl-opengl.dir/dpf/dgl/src/SubWidgetPrivateData.cpp.s
.PHONY : dpf/dgl/src/SubWidgetPrivateData.cpp.s

dpf/dgl/src/TopLevelWidget.o: dpf/dgl/src/TopLevelWidget.cpp.o
.PHONY : dpf/dgl/src/TopLevelWidget.o

# target to build an object file
dpf/dgl/src/TopLevelWidget.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dgl-opengl.dir/build.make CMakeFiles/dgl-opengl.dir/dpf/dgl/src/TopLevelWidget.cpp.o
.PHONY : dpf/dgl/src/TopLevelWidget.cpp.o

dpf/dgl/src/TopLevelWidget.i: dpf/dgl/src/TopLevelWidget.cpp.i
.PHONY : dpf/dgl/src/TopLevelWidget.i

# target to preprocess a source file
dpf/dgl/src/TopLevelWidget.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dgl-opengl.dir/build.make CMakeFiles/dgl-opengl.dir/dpf/dgl/src/TopLevelWidget.cpp.i
.PHONY : dpf/dgl/src/TopLevelWidget.cpp.i

dpf/dgl/src/TopLevelWidget.s: dpf/dgl/src/TopLevelWidget.cpp.s
.PHONY : dpf/dgl/src/TopLevelWidget.s

# target to generate assembly for a file
dpf/dgl/src/TopLevelWidget.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dgl-opengl.dir/build.make CMakeFiles/dgl-opengl.dir/dpf/dgl/src/TopLevelWidget.cpp.s
.PHONY : dpf/dgl/src/TopLevelWidget.cpp.s

dpf/dgl/src/TopLevelWidgetPrivateData.o: dpf/dgl/src/TopLevelWidgetPrivateData.cpp.o
.PHONY : dpf/dgl/src/TopLevelWidgetPrivateData.o

# target to build an object file
dpf/dgl/src/TopLevelWidgetPrivateData.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dgl-opengl.dir/build.make CMakeFiles/dgl-opengl.dir/dpf/dgl/src/TopLevelWidgetPrivateData.cpp.o
.PHONY : dpf/dgl/src/TopLevelWidgetPrivateData.cpp.o

dpf/dgl/src/TopLevelWidgetPrivateData.i: dpf/dgl/src/TopLevelWidgetPrivateData.cpp.i
.PHONY : dpf/dgl/src/TopLevelWidgetPrivateData.i

# target to preprocess a source file
dpf/dgl/src/TopLevelWidgetPrivateData.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dgl-opengl.dir/build.make CMakeFiles/dgl-opengl.dir/dpf/dgl/src/TopLevelWidgetPrivateData.cpp.i
.PHONY : dpf/dgl/src/TopLevelWidgetPrivateData.cpp.i

dpf/dgl/src/TopLevelWidgetPrivateData.s: dpf/dgl/src/TopLevelWidgetPrivateData.cpp.s
.PHONY : dpf/dgl/src/TopLevelWidgetPrivateData.s

# target to generate assembly for a file
dpf/dgl/src/TopLevelWidgetPrivateData.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dgl-opengl.dir/build.make CMakeFiles/dgl-opengl.dir/dpf/dgl/src/TopLevelWidgetPrivateData.cpp.s
.PHONY : dpf/dgl/src/TopLevelWidgetPrivateData.cpp.s

dpf/dgl/src/Widget.o: dpf/dgl/src/Widget.cpp.o
.PHONY : dpf/dgl/src/Widget.o

# target to build an object file
dpf/dgl/src/Widget.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dgl-opengl.dir/build.make CMakeFiles/dgl-opengl.dir/dpf/dgl/src/Widget.cpp.o
.PHONY : dpf/dgl/src/Widget.cpp.o

dpf/dgl/src/Widget.i: dpf/dgl/src/Widget.cpp.i
.PHONY : dpf/dgl/src/Widget.i

# target to preprocess a source file
dpf/dgl/src/Widget.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dgl-opengl.dir/build.make CMakeFiles/dgl-opengl.dir/dpf/dgl/src/Widget.cpp.i
.PHONY : dpf/dgl/src/Widget.cpp.i

dpf/dgl/src/Widget.s: dpf/dgl/src/Widget.cpp.s
.PHONY : dpf/dgl/src/Widget.s

# target to generate assembly for a file
dpf/dgl/src/Widget.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dgl-opengl.dir/build.make CMakeFiles/dgl-opengl.dir/dpf/dgl/src/Widget.cpp.s
.PHONY : dpf/dgl/src/Widget.cpp.s

dpf/dgl/src/WidgetPrivateData.o: dpf/dgl/src/WidgetPrivateData.cpp.o
.PHONY : dpf/dgl/src/WidgetPrivateData.o

# target to build an object file
dpf/dgl/src/WidgetPrivateData.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dgl-opengl.dir/build.make CMakeFiles/dgl-opengl.dir/dpf/dgl/src/WidgetPrivateData.cpp.o
.PHONY : dpf/dgl/src/WidgetPrivateData.cpp.o

dpf/dgl/src/WidgetPrivateData.i: dpf/dgl/src/WidgetPrivateData.cpp.i
.PHONY : dpf/dgl/src/WidgetPrivateData.i

# target to preprocess a source file
dpf/dgl/src/WidgetPrivateData.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dgl-opengl.dir/build.make CMakeFiles/dgl-opengl.dir/dpf/dgl/src/WidgetPrivateData.cpp.i
.PHONY : dpf/dgl/src/WidgetPrivateData.cpp.i

dpf/dgl/src/WidgetPrivateData.s: dpf/dgl/src/WidgetPrivateData.cpp.s
.PHONY : dpf/dgl/src/WidgetPrivateData.s

# target to generate assembly for a file
dpf/dgl/src/WidgetPrivateData.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dgl-opengl.dir/build.make CMakeFiles/dgl-opengl.dir/dpf/dgl/src/WidgetPrivateData.cpp.s
.PHONY : dpf/dgl/src/WidgetPrivateData.cpp.s

dpf/dgl/src/Window.o: dpf/dgl/src/Window.cpp.o
.PHONY : dpf/dgl/src/Window.o

# target to build an object file
dpf/dgl/src/Window.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dgl-opengl.dir/build.make CMakeFiles/dgl-opengl.dir/dpf/dgl/src/Window.cpp.o
.PHONY : dpf/dgl/src/Window.cpp.o

dpf/dgl/src/Window.i: dpf/dgl/src/Window.cpp.i
.PHONY : dpf/dgl/src/Window.i

# target to preprocess a source file
dpf/dgl/src/Window.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dgl-opengl.dir/build.make CMakeFiles/dgl-opengl.dir/dpf/dgl/src/Window.cpp.i
.PHONY : dpf/dgl/src/Window.cpp.i

dpf/dgl/src/Window.s: dpf/dgl/src/Window.cpp.s
.PHONY : dpf/dgl/src/Window.s

# target to generate assembly for a file
dpf/dgl/src/Window.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dgl-opengl.dir/build.make CMakeFiles/dgl-opengl.dir/dpf/dgl/src/Window.cpp.s
.PHONY : dpf/dgl/src/Window.cpp.s

dpf/dgl/src/WindowPrivateData.o: dpf/dgl/src/WindowPrivateData.cpp.o
.PHONY : dpf/dgl/src/WindowPrivateData.o

# target to build an object file
dpf/dgl/src/WindowPrivateData.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dgl-opengl.dir/build.make CMakeFiles/dgl-opengl.dir/dpf/dgl/src/WindowPrivateData.cpp.o
.PHONY : dpf/dgl/src/WindowPrivateData.cpp.o

dpf/dgl/src/WindowPrivateData.i: dpf/dgl/src/WindowPrivateData.cpp.i
.PHONY : dpf/dgl/src/WindowPrivateData.i

# target to preprocess a source file
dpf/dgl/src/WindowPrivateData.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dgl-opengl.dir/build.make CMakeFiles/dgl-opengl.dir/dpf/dgl/src/WindowPrivateData.cpp.i
.PHONY : dpf/dgl/src/WindowPrivateData.cpp.i

dpf/dgl/src/WindowPrivateData.s: dpf/dgl/src/WindowPrivateData.cpp.s
.PHONY : dpf/dgl/src/WindowPrivateData.s

# target to generate assembly for a file
dpf/dgl/src/WindowPrivateData.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dgl-opengl.dir/build.make CMakeFiles/dgl-opengl.dir/dpf/dgl/src/WindowPrivateData.cpp.s
.PHONY : dpf/dgl/src/WindowPrivateData.cpp.s

dpf/dgl/src/pugl.o: dpf/dgl/src/pugl.cpp.o
.PHONY : dpf/dgl/src/pugl.o

# target to build an object file
dpf/dgl/src/pugl.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dgl-opengl.dir/build.make CMakeFiles/dgl-opengl.dir/dpf/dgl/src/pugl.cpp.o
.PHONY : dpf/dgl/src/pugl.cpp.o

dpf/dgl/src/pugl.i: dpf/dgl/src/pugl.cpp.i
.PHONY : dpf/dgl/src/pugl.i

# target to preprocess a source file
dpf/dgl/src/pugl.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dgl-opengl.dir/build.make CMakeFiles/dgl-opengl.dir/dpf/dgl/src/pugl.cpp.i
.PHONY : dpf/dgl/src/pugl.cpp.i

dpf/dgl/src/pugl.s: dpf/dgl/src/pugl.cpp.s
.PHONY : dpf/dgl/src/pugl.s

# target to generate assembly for a file
dpf/dgl/src/pugl.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dgl-opengl.dir/build.make CMakeFiles/dgl-opengl.dir/dpf/dgl/src/pugl.cpp.s
.PHONY : dpf/dgl/src/pugl.cpp.s

dpf/distrho/DistrhoPluginMain.o: dpf/distrho/DistrhoPluginMain.cpp.o
.PHONY : dpf/distrho/DistrhoPluginMain.o

# target to build an object file
dpf/distrho/DistrhoPluginMain.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VoyeSeq-jack.dir/build.make CMakeFiles/VoyeSeq-jack.dir/dpf/distrho/DistrhoPluginMain.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VoyeSeq-lv2.dir/build.make CMakeFiles/VoyeSeq-lv2.dir/dpf/distrho/DistrhoPluginMain.cpp.o
.PHONY : dpf/distrho/DistrhoPluginMain.cpp.o

dpf/distrho/DistrhoPluginMain.i: dpf/distrho/DistrhoPluginMain.cpp.i
.PHONY : dpf/distrho/DistrhoPluginMain.i

# target to preprocess a source file
dpf/distrho/DistrhoPluginMain.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VoyeSeq-jack.dir/build.make CMakeFiles/VoyeSeq-jack.dir/dpf/distrho/DistrhoPluginMain.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VoyeSeq-lv2.dir/build.make CMakeFiles/VoyeSeq-lv2.dir/dpf/distrho/DistrhoPluginMain.cpp.i
.PHONY : dpf/distrho/DistrhoPluginMain.cpp.i

dpf/distrho/DistrhoPluginMain.s: dpf/distrho/DistrhoPluginMain.cpp.s
.PHONY : dpf/distrho/DistrhoPluginMain.s

# target to generate assembly for a file
dpf/distrho/DistrhoPluginMain.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VoyeSeq-jack.dir/build.make CMakeFiles/VoyeSeq-jack.dir/dpf/distrho/DistrhoPluginMain.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VoyeSeq-lv2.dir/build.make CMakeFiles/VoyeSeq-lv2.dir/dpf/distrho/DistrhoPluginMain.cpp.s
.PHONY : dpf/distrho/DistrhoPluginMain.cpp.s

dpf/distrho/DistrhoUIMain.o: dpf/distrho/DistrhoUIMain.cpp.o
.PHONY : dpf/distrho/DistrhoUIMain.o

# target to build an object file
dpf/distrho/DistrhoUIMain.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VoyeSeq-jack.dir/build.make CMakeFiles/VoyeSeq-jack.dir/dpf/distrho/DistrhoUIMain.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VoyeSeq-lv2-ui.dir/build.make CMakeFiles/VoyeSeq-lv2-ui.dir/dpf/distrho/DistrhoUIMain.cpp.o
.PHONY : dpf/distrho/DistrhoUIMain.cpp.o

dpf/distrho/DistrhoUIMain.i: dpf/distrho/DistrhoUIMain.cpp.i
.PHONY : dpf/distrho/DistrhoUIMain.i

# target to preprocess a source file
dpf/distrho/DistrhoUIMain.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VoyeSeq-jack.dir/build.make CMakeFiles/VoyeSeq-jack.dir/dpf/distrho/DistrhoUIMain.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VoyeSeq-lv2-ui.dir/build.make CMakeFiles/VoyeSeq-lv2-ui.dir/dpf/distrho/DistrhoUIMain.cpp.i
.PHONY : dpf/distrho/DistrhoUIMain.cpp.i

dpf/distrho/DistrhoUIMain.s: dpf/distrho/DistrhoUIMain.cpp.s
.PHONY : dpf/distrho/DistrhoUIMain.s

# target to generate assembly for a file
dpf/distrho/DistrhoUIMain.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VoyeSeq-jack.dir/build.make CMakeFiles/VoyeSeq-jack.dir/dpf/distrho/DistrhoUIMain.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VoyeSeq-lv2-ui.dir/build.make CMakeFiles/VoyeSeq-lv2-ui.dir/dpf/distrho/DistrhoUIMain.cpp.s
.PHONY : dpf/distrho/DistrhoUIMain.cpp.s

dpf/utils/lv2-ttl-generator/lv2_ttl_generator.o: dpf/utils/lv2-ttl-generator/lv2_ttl_generator.c.o
.PHONY : dpf/utils/lv2-ttl-generator/lv2_ttl_generator.o

# target to build an object file
dpf/utils/lv2-ttl-generator/lv2_ttl_generator.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lv2_ttl_generator.dir/build.make CMakeFiles/lv2_ttl_generator.dir/dpf/utils/lv2-ttl-generator/lv2_ttl_generator.c.o
.PHONY : dpf/utils/lv2-ttl-generator/lv2_ttl_generator.c.o

dpf/utils/lv2-ttl-generator/lv2_ttl_generator.i: dpf/utils/lv2-ttl-generator/lv2_ttl_generator.c.i
.PHONY : dpf/utils/lv2-ttl-generator/lv2_ttl_generator.i

# target to preprocess a source file
dpf/utils/lv2-ttl-generator/lv2_ttl_generator.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lv2_ttl_generator.dir/build.make CMakeFiles/lv2_ttl_generator.dir/dpf/utils/lv2-ttl-generator/lv2_ttl_generator.c.i
.PHONY : dpf/utils/lv2-ttl-generator/lv2_ttl_generator.c.i

dpf/utils/lv2-ttl-generator/lv2_ttl_generator.s: dpf/utils/lv2-ttl-generator/lv2_ttl_generator.c.s
.PHONY : dpf/utils/lv2-ttl-generator/lv2_ttl_generator.s

# target to generate assembly for a file
dpf/utils/lv2-ttl-generator/lv2_ttl_generator.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lv2_ttl_generator.dir/build.make CMakeFiles/lv2_ttl_generator.dir/dpf/utils/lv2-ttl-generator/lv2_ttl_generator.c.s
.PHONY : dpf/utils/lv2-ttl-generator/lv2_ttl_generator.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... VoyeSeq"
	@echo "... VoyeSeq-dsp"
	@echo "... VoyeSeq-jack"
	@echo "... VoyeSeq-lv2"
	@echo "... VoyeSeq-lv2-ui"
	@echo "... VoyeSeq-ui"
	@echo "... dgl-opengl"
	@echo "... lv2_ttl_generator"
	@echo "... VoyeRenderer.o"
	@echo "... VoyeRenderer.i"
	@echo "... VoyeRenderer.s"
	@echo "... VoyeSeqPlugin.o"
	@echo "... VoyeSeqPlugin.i"
	@echo "... VoyeSeqPlugin.s"
	@echo "... VoyeSeqUI.o"
	@echo "... VoyeSeqUI.i"
	@echo "... VoyeSeqUI.s"
	@echo "... _dpf_empty.o"
	@echo "... _dpf_empty.i"
	@echo "... _dpf_empty.s"
	@echo "... dpf/dgl/src/Application.o"
	@echo "... dpf/dgl/src/Application.i"
	@echo "... dpf/dgl/src/Application.s"
	@echo "... dpf/dgl/src/ApplicationPrivateData.o"
	@echo "... dpf/dgl/src/ApplicationPrivateData.i"
	@echo "... dpf/dgl/src/ApplicationPrivateData.s"
	@echo "... dpf/dgl/src/Color.o"
	@echo "... dpf/dgl/src/Color.i"
	@echo "... dpf/dgl/src/Color.s"
	@echo "... dpf/dgl/src/EventHandlers.o"
	@echo "... dpf/dgl/src/EventHandlers.i"
	@echo "... dpf/dgl/src/EventHandlers.s"
	@echo "... dpf/dgl/src/Geometry.o"
	@echo "... dpf/dgl/src/Geometry.i"
	@echo "... dpf/dgl/src/Geometry.s"
	@echo "... dpf/dgl/src/ImageBase.o"
	@echo "... dpf/dgl/src/ImageBase.i"
	@echo "... dpf/dgl/src/ImageBase.s"
	@echo "... dpf/dgl/src/ImageBaseWidgets.o"
	@echo "... dpf/dgl/src/ImageBaseWidgets.i"
	@echo "... dpf/dgl/src/ImageBaseWidgets.s"
	@echo "... dpf/dgl/src/Layout.o"
	@echo "... dpf/dgl/src/Layout.i"
	@echo "... dpf/dgl/src/Layout.s"
	@echo "... dpf/dgl/src/NanoVG.o"
	@echo "... dpf/dgl/src/NanoVG.i"
	@echo "... dpf/dgl/src/NanoVG.s"
	@echo "... dpf/dgl/src/OpenGL.o"
	@echo "... dpf/dgl/src/OpenGL.i"
	@echo "... dpf/dgl/src/OpenGL.s"
	@echo "... dpf/dgl/src/OpenGL2.o"
	@echo "... dpf/dgl/src/OpenGL2.i"
	@echo "... dpf/dgl/src/OpenGL2.s"
	@echo "... dpf/dgl/src/Resources.o"
	@echo "... dpf/dgl/src/Resources.i"
	@echo "... dpf/dgl/src/Resources.s"
	@echo "... dpf/dgl/src/SubWidget.o"
	@echo "... dpf/dgl/src/SubWidget.i"
	@echo "... dpf/dgl/src/SubWidget.s"
	@echo "... dpf/dgl/src/SubWidgetPrivateData.o"
	@echo "... dpf/dgl/src/SubWidgetPrivateData.i"
	@echo "... dpf/dgl/src/SubWidgetPrivateData.s"
	@echo "... dpf/dgl/src/TopLevelWidget.o"
	@echo "... dpf/dgl/src/TopLevelWidget.i"
	@echo "... dpf/dgl/src/TopLevelWidget.s"
	@echo "... dpf/dgl/src/TopLevelWidgetPrivateData.o"
	@echo "... dpf/dgl/src/TopLevelWidgetPrivateData.i"
	@echo "... dpf/dgl/src/TopLevelWidgetPrivateData.s"
	@echo "... dpf/dgl/src/Widget.o"
	@echo "... dpf/dgl/src/Widget.i"
	@echo "... dpf/dgl/src/Widget.s"
	@echo "... dpf/dgl/src/WidgetPrivateData.o"
	@echo "... dpf/dgl/src/WidgetPrivateData.i"
	@echo "... dpf/dgl/src/WidgetPrivateData.s"
	@echo "... dpf/dgl/src/Window.o"
	@echo "... dpf/dgl/src/Window.i"
	@echo "... dpf/dgl/src/Window.s"
	@echo "... dpf/dgl/src/WindowPrivateData.o"
	@echo "... dpf/dgl/src/WindowPrivateData.i"
	@echo "... dpf/dgl/src/WindowPrivateData.s"
	@echo "... dpf/dgl/src/pugl.o"
	@echo "... dpf/dgl/src/pugl.i"
	@echo "... dpf/dgl/src/pugl.s"
	@echo "... dpf/distrho/DistrhoPluginMain.o"
	@echo "... dpf/distrho/DistrhoPluginMain.i"
	@echo "... dpf/distrho/DistrhoPluginMain.s"
	@echo "... dpf/distrho/DistrhoUIMain.o"
	@echo "... dpf/distrho/DistrhoUIMain.i"
	@echo "... dpf/distrho/DistrhoUIMain.s"
	@echo "... dpf/utils/lv2-ttl-generator/lv2_ttl_generator.o"
	@echo "... dpf/utils/lv2-ttl-generator/lv2_ttl_generator.i"
	@echo "... dpf/utils/lv2-ttl-generator/lv2_ttl_generator.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

